### ISSUE TITLE
Finalize release 1.8

### ISSUE THREAD

**Issue by thiell** [cea-hpc/clustershell#360]
TODO for release 1.8. Feel free to add missing items.

## Misc

* [x] sphinx: fix a few issues, like broken links in [clush](http://clustershell.readthedocs.io/en/latest/tools/clush.html) doc
* [x] update universal specfile including fixes from Fedora and SUSE reviews (and maybe add a note packaging changes)
* [ ] readily available on openSUSE Tumbleweed

## Release notes

This should be added to the [release notes](http://clustershell.readthedocs.io/en/latest/release.html).

* [x] Dropped support for Python 2.4 and 2.5; Python 2.6+ is supported (#239)
* [x] New Python 3 support (3.4+) (#337)
* [x] `nodeset` can now handle numeric node names (#338)
* [x] New `EventHandler` API (#232)
* [x] sphinx: 1.7 -> 1.8 migration path for `EventHandler`
* [x] `task.shell()` has a new `stdin` (boolean) argument (#333)
* [x] other bug fixes ([milestone 1.8](https://github.com/cea-hpc/clustershell/issues?utf8=%E2%9C%93&q=is%3Aissue+milestone%3A1.8))
